/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 6
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_header_token1 = 1,
  aux_sym_header_token2 = 2,
  aux_sym_header_token3 = 3,
  aux_sym_param_directive_token1 = 4,
  anon_sym_COLON = 5,
  aux_sym_param_directive_token2 = 6,
  aux_sym_column_directive_token1 = 7,
  aux_sym_timeout_directive_token1 = 8,
  anon_sym_ATif_DASHpresent = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_ATendif = 12,
  anon_sym_ATwhen = 13,
  anon_sym_ATend = 14,
  anon_sym_ATchoose = 15,
  anon_sym_ATcase = 16,
  anon_sym_ATdefault = 17,
  anon_sym_ATorder_DASHby = 18,
  anon_sym_ATkey = 19,
  anon_sym_ATfilter_DASHtree_BANG = 20,
  anon_sym_ATfilter_DASHtree = 21,
  anon_sym_ATpredicate = 22,
  anon_sym_ATin = 23,
  anon_sym_COMMA = 24,
  anon_sym_EQ = 25,
  anon_sym_BANG_EQ = 26,
  anon_sym_LT_GT = 27,
  aux_sym_literal_token1 = 28,
  aux_sym_literal_token2 = 29,
  anon_sym_true = 30,
  anon_sym_false = 31,
  sym_comment = 32,
  sym_block_comment = 33,
  sym_quoted_ident = 34,
  sym_param_ref = 35,
  sym_sql_token = 36,
  sym_document = 37,
  sym__item = 38,
  sym__construct = 39,
  sym_header = 40,
  sym_param_directive = 41,
  sym_column_directive = 42,
  sym_timeout_directive = 43,
  sym_if_present_block = 44,
  sym_when_block = 45,
  sym_choose_block = 46,
  sym_case_clause = 47,
  sym_default_clause = 48,
  sym_order_by_block = 49,
  sym_key_clause = 50,
  sym_filter_tree_block = 51,
  sym_predicate_clause = 52,
  sym_in_expr = 53,
  sym_parameter_list = 54,
  sym_comparison = 55,
  sym_literal = 56,
  sym__sql_content = 57,
  sym_string = 58,
  aux_sym_document_repeat1 = 59,
  aux_sym_if_present_block_repeat1 = 60,
  aux_sym_choose_block_repeat1 = 61,
  aux_sym_order_by_block_repeat1 = 62,
  aux_sym_filter_tree_block_repeat1 = 63,
  aux_sym_parameter_list_repeat1 = 64,
  alias_sym_case_name = 65,
  alias_sym_column_name = 66,
  alias_sym_key_name = 67,
  alias_sym_predicate_name = 68,
  alias_sym_query_name = 69,
  alias_sym_timeout_value = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_header_token1] = "header_marker",
  [aux_sym_header_token2] = "parameter",
  [aux_sym_header_token3] = "annotation",
  [aux_sym_param_directive_token1] = "directive_marker",
  [anon_sym_COLON] = ":",
  [aux_sym_param_directive_token2] = "type_name",
  [aux_sym_column_directive_token1] = "directive_marker",
  [aux_sym_timeout_directive_token1] = "directive_marker",
  [anon_sym_ATif_DASHpresent] = "@if-present",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_ATendif] = "@endif",
  [anon_sym_ATwhen] = "@when",
  [anon_sym_ATend] = "@end",
  [anon_sym_ATchoose] = "@choose",
  [anon_sym_ATcase] = "@case",
  [anon_sym_ATdefault] = "@default",
  [anon_sym_ATorder_DASHby] = "@order-by",
  [anon_sym_ATkey] = "@key",
  [anon_sym_ATfilter_DASHtree_BANG] = "@filter-tree!",
  [anon_sym_ATfilter_DASHtree] = "@filter-tree",
  [anon_sym_ATpredicate] = "@predicate",
  [anon_sym_ATin] = "@in",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_GT] = "<>",
  [aux_sym_literal_token1] = "literal_token1",
  [aux_sym_literal_token2] = "literal_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_comment] = "comment",
  [sym_block_comment] = "block_comment",
  [sym_quoted_ident] = "quoted_ident",
  [sym_param_ref] = "param_ref",
  [sym_sql_token] = "sql_token",
  [sym_document] = "document",
  [sym__item] = "_item",
  [sym__construct] = "_construct",
  [sym_header] = "header",
  [sym_param_directive] = "param_directive",
  [sym_column_directive] = "column_directive",
  [sym_timeout_directive] = "timeout_directive",
  [sym_if_present_block] = "if_present_block",
  [sym_when_block] = "when_block",
  [sym_choose_block] = "choose_block",
  [sym_case_clause] = "case_clause",
  [sym_default_clause] = "default_clause",
  [sym_order_by_block] = "order_by_block",
  [sym_key_clause] = "key_clause",
  [sym_filter_tree_block] = "filter_tree_block",
  [sym_predicate_clause] = "predicate_clause",
  [sym_in_expr] = "in_expr",
  [sym_parameter_list] = "parameter_list",
  [sym_comparison] = "comparison",
  [sym_literal] = "literal",
  [sym__sql_content] = "_sql_content",
  [sym_string] = "string",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_if_present_block_repeat1] = "if_present_block_repeat1",
  [aux_sym_choose_block_repeat1] = "choose_block_repeat1",
  [aux_sym_order_by_block_repeat1] = "order_by_block_repeat1",
  [aux_sym_filter_tree_block_repeat1] = "filter_tree_block_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [alias_sym_case_name] = "case_name",
  [alias_sym_column_name] = "column_name",
  [alias_sym_key_name] = "key_name",
  [alias_sym_predicate_name] = "predicate_name",
  [alias_sym_query_name] = "query_name",
  [alias_sym_timeout_value] = "timeout_value",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_header_token1] = aux_sym_header_token1,
  [aux_sym_header_token2] = aux_sym_header_token2,
  [aux_sym_header_token3] = aux_sym_header_token3,
  [aux_sym_param_directive_token1] = aux_sym_param_directive_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_param_directive_token2] = aux_sym_param_directive_token2,
  [aux_sym_column_directive_token1] = aux_sym_param_directive_token1,
  [aux_sym_timeout_directive_token1] = aux_sym_param_directive_token1,
  [anon_sym_ATif_DASHpresent] = anon_sym_ATif_DASHpresent,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_ATendif] = anon_sym_ATendif,
  [anon_sym_ATwhen] = anon_sym_ATwhen,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_ATchoose] = anon_sym_ATchoose,
  [anon_sym_ATcase] = anon_sym_ATcase,
  [anon_sym_ATdefault] = anon_sym_ATdefault,
  [anon_sym_ATorder_DASHby] = anon_sym_ATorder_DASHby,
  [anon_sym_ATkey] = anon_sym_ATkey,
  [anon_sym_ATfilter_DASHtree_BANG] = anon_sym_ATfilter_DASHtree_BANG,
  [anon_sym_ATfilter_DASHtree] = anon_sym_ATfilter_DASHtree,
  [anon_sym_ATpredicate] = anon_sym_ATpredicate,
  [anon_sym_ATin] = anon_sym_ATin,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [aux_sym_literal_token1] = aux_sym_literal_token1,
  [aux_sym_literal_token2] = aux_sym_literal_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_comment] = sym_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_quoted_ident] = sym_quoted_ident,
  [sym_param_ref] = sym_param_ref,
  [sym_sql_token] = sym_sql_token,
  [sym_document] = sym_document,
  [sym__item] = sym__item,
  [sym__construct] = sym__construct,
  [sym_header] = sym_header,
  [sym_param_directive] = sym_param_directive,
  [sym_column_directive] = sym_column_directive,
  [sym_timeout_directive] = sym_timeout_directive,
  [sym_if_present_block] = sym_if_present_block,
  [sym_when_block] = sym_when_block,
  [sym_choose_block] = sym_choose_block,
  [sym_case_clause] = sym_case_clause,
  [sym_default_clause] = sym_default_clause,
  [sym_order_by_block] = sym_order_by_block,
  [sym_key_clause] = sym_key_clause,
  [sym_filter_tree_block] = sym_filter_tree_block,
  [sym_predicate_clause] = sym_predicate_clause,
  [sym_in_expr] = sym_in_expr,
  [sym_parameter_list] = sym_parameter_list,
  [sym_comparison] = sym_comparison,
  [sym_literal] = sym_literal,
  [sym__sql_content] = sym__sql_content,
  [sym_string] = sym_string,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_if_present_block_repeat1] = aux_sym_if_present_block_repeat1,
  [aux_sym_choose_block_repeat1] = aux_sym_choose_block_repeat1,
  [aux_sym_order_by_block_repeat1] = aux_sym_order_by_block_repeat1,
  [aux_sym_filter_tree_block_repeat1] = aux_sym_filter_tree_block_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [alias_sym_case_name] = alias_sym_case_name,
  [alias_sym_column_name] = alias_sym_column_name,
  [alias_sym_key_name] = alias_sym_key_name,
  [alias_sym_predicate_name] = alias_sym_predicate_name,
  [alias_sym_query_name] = alias_sym_query_name,
  [alias_sym_timeout_value] = alias_sym_timeout_value,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_header_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_token3] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_param_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_param_directive_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_column_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_timeout_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATif_DASHpresent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATendif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATwhen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATchoose] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATcase] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATdefault] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATorder_DASHby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATkey] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATfilter_DASHtree_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATfilter_DASHtree] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATpredicate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_param_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_sql_token] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym__construct] = {
    .visible = false,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_param_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_column_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_timeout_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_if_present_block] = {
    .visible = true,
    .named = true,
  },
  [sym_when_block] = {
    .visible = true,
    .named = true,
  },
  [sym_choose_block] = {
    .visible = true,
    .named = true,
  },
  [sym_case_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_default_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_order_by_block] = {
    .visible = true,
    .named = true,
  },
  [sym_key_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_tree_block] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_in_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__sql_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_present_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_choose_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_order_by_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_filter_tree_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_case_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_column_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_key_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_predicate_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_query_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_timeout_value] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_annotation = 1,
  field_guards = 2,
  field_name = 3,
  field_op = 4,
  field_param = 5,
  field_type = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_annotation] = "annotation",
  [field_guards] = "guards",
  [field_name] = "name",
  [field_op] = "op",
  [field_param] = "param",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 3},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 10, .length = 1},
  [10] = {.index = 10, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_value, 1},
  [1] =
    {field_annotation, 2},
    {field_name, 1},
  [3] =
    {field_name, 1},
    {field_type, 3},
  [5] =
    {field_guards, 2},
  [6] =
    {field_param, 2},
  [7] =
    {field_op, 3},
    {field_param, 2},
    {field_value, 4},
  [10] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_timeout_value,
  },
  [2] = {
    [1] = alias_sym_query_name,
  },
  [4] = {
    [1] = alias_sym_column_name,
  },
  [8] = {
    [2] = alias_sym_case_name,
  },
  [9] = {
    [2] = alias_sym_key_name,
  },
  [10] = {
    [2] = alias_sym_predicate_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 21,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 22,
  [35] = 35,
  [36] = 36,
  [37] = 21,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
};

static const TSCharacterRange sym_sql_token_character_set_1[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'(', ','}, {'.', '.'}, {'0', '9'},
  {';', '?'}, {'A', 'Z'}, {'\\', '_'}, {'a', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(90);
      ADVANCE_MAP(
        '!', 14,
        '"', 4,
        '\'', 6,
        '(', 108,
        ')', 109,
        ',', 122,
        '-', 10,
        '/', 7,
        ':', 102,
        '<', 15,
        '=', 123,
        '@', 24,
        '[', 16,
        '`', 17,
        'f', 92,
        't', 96,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 4,
        '\'', 6,
        '-', 161,
        '/', 159,
        ':', 163,
        '@', 27,
        '[', 162,
        '`', 17,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0) ADVANCE(164);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 4,
        '\'', 6,
        '-', 161,
        '/', 159,
        ':', 163,
        '@', 46,
        '[', 162,
        '`', 17,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0) ADVANCE(164);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(156);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '-') ADVANCE(87);
      if (lookahead == ':') ADVANCE(88);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 't') ADVANCE(68);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(126);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(154);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(65);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(81);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(124);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(125);
      END_STATE();
    case 16:
      if (lookahead == ']') ADVANCE(155);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '`') ADVANCE(157);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(73);
      if (lookahead == 'h') ADVANCE(63);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(83);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(85);
      END_STATE();
    case 24:
      ADVANCE_MAP(
        'c', 19,
        'd', 32,
        'e', 59,
        'f', 53,
        'i', 48,
        'k', 33,
        'o', 66,
        'p', 69,
        'w', 52,
      );
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(53);
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'o') ADVANCE(66);
      if (lookahead == 'w') ADVANCE(52);
      END_STATE();
    case 26:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'c') ADVANCE(18);
      if (lookahead == 'd') ADVANCE(32);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead == 'k') ADVANCE(33);
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(112);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(54);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(55);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(114);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(120);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(119);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(128);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(130);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 48:
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(121);
      END_STATE();
    case 49:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 50:
      if (lookahead == 'f') ADVANCE(110);
      END_STATE();
    case 51:
      if (lookahead == 'h') ADVANCE(63);
      END_STATE();
    case 52:
      if (lookahead == 'h') ADVANCE(40);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 58:
      if (lookahead == 'l') ADVANCE(76);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(111);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(74);
      END_STATE();
    case 65:
      if (lookahead == 'p') ADVANCE(71);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 75:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 76:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(115);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(107);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 82:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 83:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 84:
      if (lookahead == 'y') ADVANCE(117);
      END_STATE();
    case 85:
      if (lookahead == 'y') ADVANCE(116);
      END_STATE();
    case 86:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 87:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 88:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 89:
      if (eof) ADVANCE(90);
      ADVANCE_MAP(
        '"', 4,
        '\'', 6,
        '-', 160,
        '/', 159,
        ':', 163,
        '@', 25,
        '[', 162,
        '`', 17,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(89);
      if (lookahead != 0) ADVANCE(164);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_header_token1);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'a') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'e') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'e') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'l') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'r') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 's') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'u') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_header_token3);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_param_directive_token1);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_param_directive_token2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_param_directive_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_column_directive_token1);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_timeout_directive_token1);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_ATif_DASHpresent);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_ATendif);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_ATwhen);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_ATchoose);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_ATcase);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_ATdefault);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_ATorder_DASHby);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_ATkey);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_ATfilter_DASHtree_BANG);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_ATfilter_DASHtree);
      if (lookahead == '!') ADVANCE(118);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_ATpredicate);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_ATin);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_literal_token1);
      if (lookahead == '\'') ADVANCE(6);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_literal_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == ':') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '@') ADVANCE(137);
      if (lookahead == 'n') ADVANCE(134);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'a') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'a') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'a') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'c') ADVANCE(147);
      if (lookahead == 'p') ADVANCE(135);
      if (lookahead == 't') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'e') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'e') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'i') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'l') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'm') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'm') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'm') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'm') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'n') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'o') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'o') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'r') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 't') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'u') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'u') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(153);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_quoted_ident);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_quoted_ident);
      if (lookahead == '"') ADVANCE(4);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_quoted_ident);
      if (lookahead == '`') ADVANCE(17);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_param_ref);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(158);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_sql_token);
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_sql_token);
      if (lookahead == '-') ADVANCE(133);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_sql_token);
      if (lookahead == '-') ADVANCE(153);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_sql_token);
      if (lookahead == ']') ADVANCE(155);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_sql_token);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(158);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_sql_token);
      if ((!eof && set_contains(sym_sql_token_character_set_1, 12, lookahead))) ADVANCE(164);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 89},
  [2] = {.lex_state = 89},
  [3] = {.lex_state = 89},
  [4] = {.lex_state = 89},
  [5] = {.lex_state = 89},
  [6] = {.lex_state = 89},
  [7] = {.lex_state = 89},
  [8] = {.lex_state = 89},
  [9] = {.lex_state = 89},
  [10] = {.lex_state = 89},
  [11] = {.lex_state = 89},
  [12] = {.lex_state = 89},
  [13] = {.lex_state = 89},
  [14] = {.lex_state = 89},
  [15] = {.lex_state = 89},
  [16] = {.lex_state = 89},
  [17] = {.lex_state = 89},
  [18] = {.lex_state = 89},
  [19] = {.lex_state = 89},
  [20] = {.lex_state = 89},
  [21] = {.lex_state = 89},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 86},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 86},
  [57] = {.lex_state = 86},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 89},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 86},
  [67] = {.lex_state = 86},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 86},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 86},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 86},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 86},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 86},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 86},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 86},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_header_token1] = ACTIONS(1),
    [aux_sym_header_token2] = ACTIONS(1),
    [aux_sym_param_directive_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_column_directive_token1] = ACTIONS(1),
    [aux_sym_timeout_directive_token1] = ACTIONS(1),
    [anon_sym_ATif_DASHpresent] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_ATwhen] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATchoose] = ACTIONS(1),
    [anon_sym_ATcase] = ACTIONS(1),
    [anon_sym_ATdefault] = ACTIONS(1),
    [anon_sym_ATorder_DASHby] = ACTIONS(1),
    [anon_sym_ATkey] = ACTIONS(1),
    [anon_sym_ATfilter_DASHtree_BANG] = ACTIONS(1),
    [anon_sym_ATfilter_DASHtree] = ACTIONS(1),
    [anon_sym_ATpredicate] = ACTIONS(1),
    [anon_sym_ATin] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [aux_sym_literal_token1] = ACTIONS(1),
    [aux_sym_literal_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
    [sym_quoted_ident] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(88),
    [sym__item] = STATE(2),
    [sym__construct] = STATE(2),
    [sym_header] = STATE(2),
    [sym_param_directive] = STATE(2),
    [sym_column_directive] = STATE(2),
    [sym_timeout_directive] = STATE(2),
    [sym_if_present_block] = STATE(2),
    [sym_when_block] = STATE(2),
    [sym_choose_block] = STATE(2),
    [sym_order_by_block] = STATE(2),
    [sym_filter_tree_block] = STATE(2),
    [sym_in_expr] = STATE(2),
    [sym__sql_content] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_header_token1] = ACTIONS(5),
    [aux_sym_param_directive_token1] = ACTIONS(7),
    [aux_sym_column_directive_token1] = ACTIONS(9),
    [aux_sym_timeout_directive_token1] = ACTIONS(11),
    [anon_sym_ATif_DASHpresent] = ACTIONS(13),
    [anon_sym_ATwhen] = ACTIONS(15),
    [anon_sym_ATchoose] = ACTIONS(17),
    [anon_sym_ATorder_DASHby] = ACTIONS(19),
    [anon_sym_ATfilter_DASHtree_BANG] = ACTIONS(21),
    [anon_sym_ATfilter_DASHtree] = ACTIONS(23),
    [anon_sym_ATin] = ACTIONS(25),
    [aux_sym_literal_token1] = ACTIONS(27),
    [sym_comment] = ACTIONS(29),
    [sym_block_comment] = ACTIONS(31),
    [sym_quoted_ident] = ACTIONS(31),
    [sym_param_ref] = ACTIONS(31),
    [sym_sql_token] = ACTIONS(29),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym__construct] = STATE(3),
    [sym_header] = STATE(3),
    [sym_param_directive] = STATE(3),
    [sym_column_directive] = STATE(3),
    [sym_timeout_directive] = STATE(3),
    [sym_if_present_block] = STATE(3),
    [sym_when_block] = STATE(3),
    [sym_choose_block] = STATE(3),
    [sym_order_by_block] = STATE(3),
    [sym_filter_tree_block] = STATE(3),
    [sym_in_expr] = STATE(3),
    [sym__sql_content] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(33),
    [aux_sym_header_token1] = ACTIONS(5),
    [aux_sym_param_directive_token1] = ACTIONS(7),
    [aux_sym_column_directive_token1] = ACTIONS(9),
    [aux_sym_timeout_directive_token1] = ACTIONS(11),
    [anon_sym_ATif_DASHpresent] = ACTIONS(13),
    [anon_sym_ATwhen] = ACTIONS(15),
    [anon_sym_ATchoose] = ACTIONS(17),
    [anon_sym_ATorder_DASHby] = ACTIONS(19),
    [anon_sym_ATfilter_DASHtree_BANG] = ACTIONS(21),
    [anon_sym_ATfilter_DASHtree] = ACTIONS(23),
    [anon_sym_ATin] = ACTIONS(25),
    [aux_sym_literal_token1] = ACTIONS(27),
    [sym_comment] = ACTIONS(35),
    [sym_block_comment] = ACTIONS(37),
    [sym_quoted_ident] = ACTIONS(37),
    [sym_param_ref] = ACTIONS(37),
    [sym_sql_token] = ACTIONS(35),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym__construct] = STATE(3),
    [sym_header] = STATE(3),
    [sym_param_directive] = STATE(3),
    [sym_column_directive] = STATE(3),
    [sym_timeout_directive] = STATE(3),
    [sym_if_present_block] = STATE(3),
    [sym_when_block] = STATE(3),
    [sym_choose_block] = STATE(3),
    [sym_order_by_block] = STATE(3),
    [sym_filter_tree_block] = STATE(3),
    [sym_in_expr] = STATE(3),
    [sym__sql_content] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(39),
    [aux_sym_header_token1] = ACTIONS(41),
    [aux_sym_param_directive_token1] = ACTIONS(44),
    [aux_sym_column_directive_token1] = ACTIONS(47),
    [aux_sym_timeout_directive_token1] = ACTIONS(50),
    [anon_sym_ATif_DASHpresent] = ACTIONS(53),
    [anon_sym_ATwhen] = ACTIONS(56),
    [anon_sym_ATchoose] = ACTIONS(59),
    [anon_sym_ATorder_DASHby] = ACTIONS(62),
    [anon_sym_ATfilter_DASHtree_BANG] = ACTIONS(65),
    [anon_sym_ATfilter_DASHtree] = ACTIONS(68),
    [anon_sym_ATin] = ACTIONS(71),
    [aux_sym_literal_token1] = ACTIONS(74),
    [sym_comment] = ACTIONS(77),
    [sym_block_comment] = ACTIONS(80),
    [sym_quoted_ident] = ACTIONS(80),
    [sym_param_ref] = ACTIONS(80),
    [sym_sql_token] = ACTIONS(77),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(85), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(83), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [23] = 2,
    ACTIONS(89), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(87), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [46] = 2,
    ACTIONS(93), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(91), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [69] = 2,
    ACTIONS(97), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(95), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [92] = 2,
    ACTIONS(101), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(99), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [115] = 2,
    ACTIONS(105), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(103), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [138] = 2,
    ACTIONS(109), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(107), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [161] = 2,
    ACTIONS(113), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(111), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [184] = 2,
    ACTIONS(117), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(115), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [207] = 2,
    ACTIONS(121), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(119), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [230] = 2,
    ACTIONS(125), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(123), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [253] = 2,
    ACTIONS(129), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(127), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [276] = 2,
    ACTIONS(133), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(131), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [299] = 2,
    ACTIONS(137), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(135), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [322] = 2,
    ACTIONS(141), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(139), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [345] = 2,
    ACTIONS(145), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(143), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [368] = 2,
    ACTIONS(149), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(147), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [391] = 2,
    ACTIONS(153), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(151), 15,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      aux_sym_timeout_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [414] = 5,
    ACTIONS(157), 1,
      aux_sym_literal_token1,
    ACTIONS(163), 1,
      sym_sql_token,
    STATE(22), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(160), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
    ACTIONS(155), 5,
      anon_sym_ATend,
      anon_sym_ATcase,
      anon_sym_ATdefault,
      anon_sym_ATkey,
      anon_sym_ATpredicate,
  [439] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(172), 1,
      sym_sql_token,
    ACTIONS(166), 3,
      anon_sym_ATend,
      anon_sym_ATdefault,
      anon_sym_ATkey,
    STATE(24), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(170), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [462] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(178), 1,
      sym_sql_token,
    ACTIONS(174), 3,
      anon_sym_ATend,
      anon_sym_ATdefault,
      anon_sym_ATkey,
    STATE(22), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(176), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [485] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(178), 1,
      sym_sql_token,
    ACTIONS(180), 3,
      anon_sym_ATend,
      anon_sym_ATcase,
      anon_sym_ATdefault,
    STATE(22), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(176), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [508] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(186), 1,
      sym_sql_token,
    ACTIONS(182), 3,
      anon_sym_ATend,
      anon_sym_ATcase,
      anon_sym_ATdefault,
    STATE(25), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(184), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [531] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(192), 1,
      sym_sql_token,
    ACTIONS(188), 2,
      anon_sym_ATend,
      anon_sym_ATpredicate,
    STATE(28), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(190), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [553] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(178), 1,
      sym_sql_token,
    ACTIONS(194), 2,
      anon_sym_ATend,
      anon_sym_ATpredicate,
    STATE(22), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(176), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [575] = 2,
    ACTIONS(153), 1,
      sym_sql_token,
    ACTIONS(151), 10,
      anon_sym_ATend,
      anon_sym_ATcase,
      anon_sym_ATdefault,
      anon_sym_ATkey,
      anon_sym_ATpredicate,
      aux_sym_literal_token1,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [591] = 5,
    ACTIONS(196), 1,
      anon_sym_ATendif,
    ACTIONS(198), 1,
      aux_sym_literal_token1,
    ACTIONS(202), 1,
      sym_sql_token,
    STATE(34), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(200), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [612] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(204), 1,
      anon_sym_ATend,
    ACTIONS(208), 1,
      sym_sql_token,
    STATE(35), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(206), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [633] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(178), 1,
      sym_sql_token,
    ACTIONS(210), 1,
      anon_sym_ATend,
    STATE(22), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(176), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [654] = 5,
    ACTIONS(198), 1,
      aux_sym_literal_token1,
    ACTIONS(212), 1,
      anon_sym_ATendif,
    ACTIONS(216), 1,
      sym_sql_token,
    STATE(30), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(214), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [675] = 5,
    ACTIONS(155), 1,
      anon_sym_ATendif,
    ACTIONS(218), 1,
      aux_sym_literal_token1,
    ACTIONS(224), 1,
      sym_sql_token,
    STATE(34), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(221), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [696] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(178), 1,
      sym_sql_token,
    ACTIONS(227), 1,
      anon_sym_ATend,
    STATE(22), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(176), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [717] = 5,
    ACTIONS(168), 1,
      aux_sym_literal_token1,
    ACTIONS(229), 1,
      anon_sym_ATend,
    ACTIONS(233), 1,
      sym_sql_token,
    STATE(32), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(231), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [738] = 2,
    ACTIONS(153), 1,
      sym_sql_token,
    ACTIONS(151), 6,
      anon_sym_ATendif,
      aux_sym_literal_token1,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [750] = 5,
    ACTIONS(235), 1,
      anon_sym_ATend,
    ACTIONS(237), 1,
      anon_sym_ATdefault,
    ACTIONS(239), 1,
      anon_sym_ATkey,
    STATE(74), 1,
      sym_default_clause,
    STATE(44), 2,
      sym_key_clause,
      aux_sym_order_by_block_repeat1,
  [767] = 5,
    ACTIONS(237), 1,
      anon_sym_ATdefault,
    ACTIONS(241), 1,
      anon_sym_ATend,
    ACTIONS(243), 1,
      anon_sym_ATcase,
    STATE(55), 1,
      sym_default_clause,
    STATE(42), 2,
      sym_case_clause,
      aux_sym_choose_block_repeat1,
  [784] = 5,
    ACTIONS(237), 1,
      anon_sym_ATdefault,
    ACTIONS(239), 1,
      anon_sym_ATkey,
    ACTIONS(245), 1,
      anon_sym_ATend,
    STATE(59), 1,
      sym_default_clause,
    STATE(38), 2,
      sym_key_clause,
      aux_sym_order_by_block_repeat1,
  [801] = 5,
    ACTIONS(237), 1,
      anon_sym_ATdefault,
    ACTIONS(243), 1,
      anon_sym_ATcase,
    ACTIONS(247), 1,
      anon_sym_ATend,
    STATE(95), 1,
      sym_default_clause,
    STATE(39), 2,
      sym_case_clause,
      aux_sym_choose_block_repeat1,
  [818] = 3,
    ACTIONS(251), 1,
      anon_sym_ATcase,
    ACTIONS(249), 2,
      anon_sym_ATend,
      anon_sym_ATdefault,
    STATE(42), 2,
      sym_case_clause,
      aux_sym_choose_block_repeat1,
  [830] = 2,
    STATE(75), 1,
      sym_literal,
    ACTIONS(254), 4,
      aux_sym_literal_token1,
      aux_sym_literal_token2,
      anon_sym_true,
      anon_sym_false,
  [840] = 3,
    ACTIONS(258), 1,
      anon_sym_ATkey,
    ACTIONS(256), 2,
      anon_sym_ATend,
      anon_sym_ATdefault,
    STATE(44), 2,
      sym_key_clause,
      aux_sym_order_by_block_repeat1,
  [852] = 3,
    ACTIONS(261), 1,
      anon_sym_ATend,
    ACTIONS(263), 1,
      anon_sym_ATpredicate,
    STATE(47), 2,
      sym_predicate_clause,
      aux_sym_filter_tree_block_repeat1,
  [863] = 1,
    ACTIONS(265), 4,
      aux_sym_literal_token1,
      aux_sym_literal_token2,
      anon_sym_true,
      anon_sym_false,
  [870] = 3,
    ACTIONS(263), 1,
      anon_sym_ATpredicate,
    ACTIONS(267), 1,
      anon_sym_ATend,
    STATE(49), 2,
      sym_predicate_clause,
      aux_sym_filter_tree_block_repeat1,
  [881] = 2,
    STATE(43), 1,
      sym_comparison,
    ACTIONS(269), 3,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
  [890] = 3,
    ACTIONS(271), 1,
      anon_sym_ATend,
    ACTIONS(273), 1,
      anon_sym_ATpredicate,
    STATE(49), 2,
      sym_predicate_clause,
      aux_sym_filter_tree_block_repeat1,
  [901] = 3,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_parameter_list_repeat1,
  [911] = 3,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_parameter_list_repeat1,
  [921] = 3,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_parameter_list_repeat1,
  [931] = 2,
    ACTIONS(287), 1,
      aux_sym_header_token2,
    STATE(68), 1,
      sym_parameter_list,
  [938] = 1,
    ACTIONS(276), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [943] = 1,
    ACTIONS(289), 1,
      anon_sym_ATend,
  [947] = 1,
    ACTIONS(291), 1,
      aux_sym_header_token2,
  [951] = 1,
    ACTIONS(293), 1,
      aux_sym_header_token2,
  [955] = 1,
    ACTIONS(295), 1,
      anon_sym_LPAREN,
  [959] = 1,
    ACTIONS(235), 1,
      anon_sym_ATend,
  [963] = 1,
    ACTIONS(297), 1,
      sym_param_ref,
  [967] = 1,
    ACTIONS(299), 1,
      aux_sym_param_directive_token2,
  [971] = 1,
    ACTIONS(301), 1,
      anon_sym_LPAREN,
  [975] = 1,
    ACTIONS(303), 1,
      anon_sym_LPAREN,
  [979] = 1,
    ACTIONS(305), 1,
      aux_sym_param_directive_token2,
  [983] = 1,
    ACTIONS(307), 1,
      aux_sym_param_directive_token2,
  [987] = 1,
    ACTIONS(309), 1,
      aux_sym_header_token2,
  [991] = 1,
    ACTIONS(311), 1,
      aux_sym_header_token2,
  [995] = 1,
    ACTIONS(313), 1,
      anon_sym_RPAREN,
  [999] = 1,
    ACTIONS(315), 1,
      anon_sym_LPAREN,
  [1003] = 1,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
  [1007] = 1,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
  [1011] = 1,
    ACTIONS(321), 1,
      aux_sym_header_token2,
  [1015] = 1,
    ACTIONS(323), 1,
      anon_sym_RPAREN,
  [1019] = 1,
    ACTIONS(325), 1,
      anon_sym_ATend,
  [1023] = 1,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
  [1027] = 1,
    ACTIONS(329), 1,
      aux_sym_header_token2,
  [1031] = 1,
    ACTIONS(331), 1,
      anon_sym_RPAREN,
  [1035] = 1,
    ACTIONS(333), 1,
      anon_sym_LPAREN,
  [1039] = 1,
    ACTIONS(335), 1,
      anon_sym_LPAREN,
  [1043] = 1,
    ACTIONS(337), 1,
      aux_sym_header_token2,
  [1047] = 1,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
  [1051] = 1,
    ACTIONS(341), 1,
      anon_sym_LPAREN,
  [1055] = 1,
    ACTIONS(343), 1,
      anon_sym_RPAREN,
  [1059] = 1,
    ACTIONS(345), 1,
      anon_sym_LPAREN,
  [1063] = 1,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
  [1067] = 1,
    ACTIONS(349), 1,
      anon_sym_LPAREN,
  [1071] = 1,
    ACTIONS(351), 1,
      aux_sym_header_token2,
  [1075] = 1,
    ACTIONS(353), 1,
      ts_builtin_sym_end,
  [1079] = 1,
    ACTIONS(355), 1,
      aux_sym_header_token2,
  [1083] = 1,
    ACTIONS(357), 1,
      aux_sym_header_token3,
  [1087] = 1,
    ACTIONS(359), 1,
      anon_sym_COLON,
  [1091] = 1,
    ACTIONS(361), 1,
      aux_sym_header_token2,
  [1095] = 1,
    ACTIONS(363), 1,
      anon_sym_COLON,
  [1099] = 1,
    ACTIONS(365), 1,
      aux_sym_header_token2,
  [1103] = 1,
    ACTIONS(241), 1,
      anon_sym_ATend,
  [1107] = 1,
    ACTIONS(367), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 23,
  [SMALL_STATE(6)] = 46,
  [SMALL_STATE(7)] = 69,
  [SMALL_STATE(8)] = 92,
  [SMALL_STATE(9)] = 115,
  [SMALL_STATE(10)] = 138,
  [SMALL_STATE(11)] = 161,
  [SMALL_STATE(12)] = 184,
  [SMALL_STATE(13)] = 207,
  [SMALL_STATE(14)] = 230,
  [SMALL_STATE(15)] = 253,
  [SMALL_STATE(16)] = 276,
  [SMALL_STATE(17)] = 299,
  [SMALL_STATE(18)] = 322,
  [SMALL_STATE(19)] = 345,
  [SMALL_STATE(20)] = 368,
  [SMALL_STATE(21)] = 391,
  [SMALL_STATE(22)] = 414,
  [SMALL_STATE(23)] = 439,
  [SMALL_STATE(24)] = 462,
  [SMALL_STATE(25)] = 485,
  [SMALL_STATE(26)] = 508,
  [SMALL_STATE(27)] = 531,
  [SMALL_STATE(28)] = 553,
  [SMALL_STATE(29)] = 575,
  [SMALL_STATE(30)] = 591,
  [SMALL_STATE(31)] = 612,
  [SMALL_STATE(32)] = 633,
  [SMALL_STATE(33)] = 654,
  [SMALL_STATE(34)] = 675,
  [SMALL_STATE(35)] = 696,
  [SMALL_STATE(36)] = 717,
  [SMALL_STATE(37)] = 738,
  [SMALL_STATE(38)] = 750,
  [SMALL_STATE(39)] = 767,
  [SMALL_STATE(40)] = 784,
  [SMALL_STATE(41)] = 801,
  [SMALL_STATE(42)] = 818,
  [SMALL_STATE(43)] = 830,
  [SMALL_STATE(44)] = 840,
  [SMALL_STATE(45)] = 852,
  [SMALL_STATE(46)] = 863,
  [SMALL_STATE(47)] = 870,
  [SMALL_STATE(48)] = 881,
  [SMALL_STATE(49)] = 890,
  [SMALL_STATE(50)] = 901,
  [SMALL_STATE(51)] = 911,
  [SMALL_STATE(52)] = 921,
  [SMALL_STATE(53)] = 931,
  [SMALL_STATE(54)] = 938,
  [SMALL_STATE(55)] = 943,
  [SMALL_STATE(56)] = 947,
  [SMALL_STATE(57)] = 951,
  [SMALL_STATE(58)] = 955,
  [SMALL_STATE(59)] = 959,
  [SMALL_STATE(60)] = 963,
  [SMALL_STATE(61)] = 967,
  [SMALL_STATE(62)] = 971,
  [SMALL_STATE(63)] = 975,
  [SMALL_STATE(64)] = 979,
  [SMALL_STATE(65)] = 983,
  [SMALL_STATE(66)] = 987,
  [SMALL_STATE(67)] = 991,
  [SMALL_STATE(68)] = 995,
  [SMALL_STATE(69)] = 999,
  [SMALL_STATE(70)] = 1003,
  [SMALL_STATE(71)] = 1007,
  [SMALL_STATE(72)] = 1011,
  [SMALL_STATE(73)] = 1015,
  [SMALL_STATE(74)] = 1019,
  [SMALL_STATE(75)] = 1023,
  [SMALL_STATE(76)] = 1027,
  [SMALL_STATE(77)] = 1031,
  [SMALL_STATE(78)] = 1035,
  [SMALL_STATE(79)] = 1039,
  [SMALL_STATE(80)] = 1043,
  [SMALL_STATE(81)] = 1047,
  [SMALL_STATE(82)] = 1051,
  [SMALL_STATE(83)] = 1055,
  [SMALL_STATE(84)] = 1059,
  [SMALL_STATE(85)] = 1063,
  [SMALL_STATE(86)] = 1067,
  [SMALL_STATE(87)] = 1071,
  [SMALL_STATE(88)] = 1075,
  [SMALL_STATE(89)] = 1079,
  [SMALL_STATE(90)] = 1083,
  [SMALL_STATE(91)] = 1087,
  [SMALL_STATE(92)] = 1091,
  [SMALL_STATE(93)] = 1095,
  [SMALL_STATE(94)] = 1099,
  [SMALL_STATE(95)] = 1103,
  [SMALL_STATE(96)] = 1107,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_tree_block, 5, 0, 6),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_tree_block, 5, 0, 6),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_block, 8, 0, 7),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_when_block, 8, 0, 7),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_directive, 4, 0, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_param_directive, 4, 0, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_directive, 4, 0, 4),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_directive, 4, 0, 4),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_expr, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in_expr, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_timeout_directive, 2, 0, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_timeout_directive, 2, 0, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_present_block, 5, 0, 5),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_present_block, 5, 0, 5),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choose_block, 5, 0, 6),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choose_block, 5, 0, 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order_by_block, 5, 0, 6),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_order_by_block, 5, 0, 6),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 3, 0, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_present_block, 6, 0, 5),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_present_block, 6, 0, 5),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choose_block, 6, 0, 6),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choose_block, 6, 0, 6),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order_by_block, 6, 0, 6),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_order_by_block, 6, 0, 6),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_tree_block, 6, 0, 6),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_tree_block, 6, 0, 6),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_block, 7, 0, 7),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_when_block, 7, 0, 7),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choose_block, 7, 0, 6),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choose_block, 7, 0, 6),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order_by_block, 7, 0, 6),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_order_by_block, 7, 0, 6),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [160] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_clause, 4, 0, 9),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_clause, 5, 0, 9),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_clause, 5, 0, 8),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_clause, 4, 0, 8),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_clause, 4, 0, 10),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_clause, 5, 0, 10),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_clause, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [224] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_clause, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_choose_block_repeat1, 2, 0, 0),
  [251] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_choose_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_order_by_block_repeat1, 2, 0, 0),
  [258] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_by_block_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 1, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filter_tree_block_repeat1, 2, 0, 0),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_filter_tree_block_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [353] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sqletch(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sqletch",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
