/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 5
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_header_token1 = 1,
  aux_sym_header_token2 = 2,
  aux_sym_header_token3 = 3,
  aux_sym_param_directive_token1 = 4,
  anon_sym_COLON = 5,
  aux_sym_param_directive_token2 = 6,
  aux_sym_column_directive_token1 = 7,
  anon_sym_ATif_DASHpresent = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_ATendif = 11,
  anon_sym_ATwhen = 12,
  anon_sym_ATend = 13,
  anon_sym_ATchoose = 14,
  anon_sym_ATcase = 15,
  anon_sym_ATdefault = 16,
  anon_sym_ATorder_DASHby = 17,
  anon_sym_ATkey = 18,
  anon_sym_ATfilter_DASHtree_BANG = 19,
  anon_sym_ATfilter_DASHtree = 20,
  anon_sym_ATpredicate = 21,
  anon_sym_ATin = 22,
  anon_sym_COMMA = 23,
  anon_sym_EQ = 24,
  anon_sym_BANG_EQ = 25,
  anon_sym_LT_GT = 26,
  aux_sym_literal_token1 = 27,
  aux_sym_literal_token2 = 28,
  anon_sym_true = 29,
  anon_sym_false = 30,
  sym_comment = 31,
  sym_block_comment = 32,
  sym_quoted_ident = 33,
  sym_param_ref = 34,
  sym_sql_token = 35,
  sym_document = 36,
  sym__item = 37,
  sym__construct = 38,
  sym_header = 39,
  sym_param_directive = 40,
  sym_column_directive = 41,
  sym_if_present_block = 42,
  sym_when_block = 43,
  sym_choose_block = 44,
  sym_case_clause = 45,
  sym_default_clause = 46,
  sym_order_by_block = 47,
  sym_key_clause = 48,
  sym_filter_tree_block = 49,
  sym_predicate_clause = 50,
  sym_in_expr = 51,
  sym_parameter_list = 52,
  sym_comparison = 53,
  sym_literal = 54,
  sym__sql_content = 55,
  sym_string = 56,
  aux_sym_document_repeat1 = 57,
  aux_sym_if_present_block_repeat1 = 58,
  aux_sym_choose_block_repeat1 = 59,
  aux_sym_order_by_block_repeat1 = 60,
  aux_sym_filter_tree_block_repeat1 = 61,
  aux_sym_parameter_list_repeat1 = 62,
  alias_sym_case_name = 63,
  alias_sym_column_name = 64,
  alias_sym_key_name = 65,
  alias_sym_predicate_name = 66,
  alias_sym_query_name = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_header_token1] = "header_marker",
  [aux_sym_header_token2] = "parameter",
  [aux_sym_header_token3] = "annotation",
  [aux_sym_param_directive_token1] = "directive_marker",
  [anon_sym_COLON] = ":",
  [aux_sym_param_directive_token2] = "type_name",
  [aux_sym_column_directive_token1] = "directive_marker",
  [anon_sym_ATif_DASHpresent] = "@if-present",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_ATendif] = "@endif",
  [anon_sym_ATwhen] = "@when",
  [anon_sym_ATend] = "@end",
  [anon_sym_ATchoose] = "@choose",
  [anon_sym_ATcase] = "@case",
  [anon_sym_ATdefault] = "@default",
  [anon_sym_ATorder_DASHby] = "@order-by",
  [anon_sym_ATkey] = "@key",
  [anon_sym_ATfilter_DASHtree_BANG] = "@filter-tree!",
  [anon_sym_ATfilter_DASHtree] = "@filter-tree",
  [anon_sym_ATpredicate] = "@predicate",
  [anon_sym_ATin] = "@in",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_GT] = "<>",
  [aux_sym_literal_token1] = "literal_token1",
  [aux_sym_literal_token2] = "literal_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_comment] = "comment",
  [sym_block_comment] = "block_comment",
  [sym_quoted_ident] = "quoted_ident",
  [sym_param_ref] = "param_ref",
  [sym_sql_token] = "sql_token",
  [sym_document] = "document",
  [sym__item] = "_item",
  [sym__construct] = "_construct",
  [sym_header] = "header",
  [sym_param_directive] = "param_directive",
  [sym_column_directive] = "column_directive",
  [sym_if_present_block] = "if_present_block",
  [sym_when_block] = "when_block",
  [sym_choose_block] = "choose_block",
  [sym_case_clause] = "case_clause",
  [sym_default_clause] = "default_clause",
  [sym_order_by_block] = "order_by_block",
  [sym_key_clause] = "key_clause",
  [sym_filter_tree_block] = "filter_tree_block",
  [sym_predicate_clause] = "predicate_clause",
  [sym_in_expr] = "in_expr",
  [sym_parameter_list] = "parameter_list",
  [sym_comparison] = "comparison",
  [sym_literal] = "literal",
  [sym__sql_content] = "_sql_content",
  [sym_string] = "string",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_if_present_block_repeat1] = "if_present_block_repeat1",
  [aux_sym_choose_block_repeat1] = "choose_block_repeat1",
  [aux_sym_order_by_block_repeat1] = "order_by_block_repeat1",
  [aux_sym_filter_tree_block_repeat1] = "filter_tree_block_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [alias_sym_case_name] = "case_name",
  [alias_sym_column_name] = "column_name",
  [alias_sym_key_name] = "key_name",
  [alias_sym_predicate_name] = "predicate_name",
  [alias_sym_query_name] = "query_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_header_token1] = aux_sym_header_token1,
  [aux_sym_header_token2] = aux_sym_header_token2,
  [aux_sym_header_token3] = aux_sym_header_token3,
  [aux_sym_param_directive_token1] = aux_sym_param_directive_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_param_directive_token2] = aux_sym_param_directive_token2,
  [aux_sym_column_directive_token1] = aux_sym_param_directive_token1,
  [anon_sym_ATif_DASHpresent] = anon_sym_ATif_DASHpresent,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_ATendif] = anon_sym_ATendif,
  [anon_sym_ATwhen] = anon_sym_ATwhen,
  [anon_sym_ATend] = anon_sym_ATend,
  [anon_sym_ATchoose] = anon_sym_ATchoose,
  [anon_sym_ATcase] = anon_sym_ATcase,
  [anon_sym_ATdefault] = anon_sym_ATdefault,
  [anon_sym_ATorder_DASHby] = anon_sym_ATorder_DASHby,
  [anon_sym_ATkey] = anon_sym_ATkey,
  [anon_sym_ATfilter_DASHtree_BANG] = anon_sym_ATfilter_DASHtree_BANG,
  [anon_sym_ATfilter_DASHtree] = anon_sym_ATfilter_DASHtree,
  [anon_sym_ATpredicate] = anon_sym_ATpredicate,
  [anon_sym_ATin] = anon_sym_ATin,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [aux_sym_literal_token1] = aux_sym_literal_token1,
  [aux_sym_literal_token2] = aux_sym_literal_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_comment] = sym_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_quoted_ident] = sym_quoted_ident,
  [sym_param_ref] = sym_param_ref,
  [sym_sql_token] = sym_sql_token,
  [sym_document] = sym_document,
  [sym__item] = sym__item,
  [sym__construct] = sym__construct,
  [sym_header] = sym_header,
  [sym_param_directive] = sym_param_directive,
  [sym_column_directive] = sym_column_directive,
  [sym_if_present_block] = sym_if_present_block,
  [sym_when_block] = sym_when_block,
  [sym_choose_block] = sym_choose_block,
  [sym_case_clause] = sym_case_clause,
  [sym_default_clause] = sym_default_clause,
  [sym_order_by_block] = sym_order_by_block,
  [sym_key_clause] = sym_key_clause,
  [sym_filter_tree_block] = sym_filter_tree_block,
  [sym_predicate_clause] = sym_predicate_clause,
  [sym_in_expr] = sym_in_expr,
  [sym_parameter_list] = sym_parameter_list,
  [sym_comparison] = sym_comparison,
  [sym_literal] = sym_literal,
  [sym__sql_content] = sym__sql_content,
  [sym_string] = sym_string,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_if_present_block_repeat1] = aux_sym_if_present_block_repeat1,
  [aux_sym_choose_block_repeat1] = aux_sym_choose_block_repeat1,
  [aux_sym_order_by_block_repeat1] = aux_sym_order_by_block_repeat1,
  [aux_sym_filter_tree_block_repeat1] = aux_sym_filter_tree_block_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [alias_sym_case_name] = alias_sym_case_name,
  [alias_sym_column_name] = alias_sym_column_name,
  [alias_sym_key_name] = alias_sym_key_name,
  [alias_sym_predicate_name] = alias_sym_predicate_name,
  [alias_sym_query_name] = alias_sym_query_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_header_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_token3] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_param_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_param_directive_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_column_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATif_DASHpresent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATendif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATwhen] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATchoose] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATcase] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATdefault] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATorder_DASHby] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATkey] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATfilter_DASHtree_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATfilter_DASHtree] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATpredicate] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_literal_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_param_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_sql_token] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym__construct] = {
    .visible = false,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_param_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_column_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_if_present_block] = {
    .visible = true,
    .named = true,
  },
  [sym_when_block] = {
    .visible = true,
    .named = true,
  },
  [sym_choose_block] = {
    .visible = true,
    .named = true,
  },
  [sym_case_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_default_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_order_by_block] = {
    .visible = true,
    .named = true,
  },
  [sym_key_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_tree_block] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_in_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__sql_content] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_present_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_choose_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_order_by_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_filter_tree_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_case_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_column_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_key_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_predicate_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_query_name] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_annotation = 1,
  field_guards = 2,
  field_name = 3,
  field_op = 4,
  field_param = 5,
  field_type = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_annotation] = "annotation",
  [field_guards] = "guards",
  [field_name] = "name",
  [field_op] = "op",
  [field_param] = "param",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 9, .length = 1},
  [9] = {.index = 9, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_annotation, 2},
    {field_name, 1},
  [2] =
    {field_name, 1},
    {field_type, 3},
  [4] =
    {field_guards, 2},
  [5] =
    {field_param, 2},
  [6] =
    {field_op, 3},
    {field_param, 2},
    {field_value, 4},
  [9] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_query_name,
  },
  [3] = {
    [1] = alias_sym_column_name,
  },
  [7] = {
    [2] = alias_sym_case_name,
  },
  [8] = {
    [2] = alias_sym_key_name,
  },
  [9] = {
    [2] = alias_sym_predicate_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 20,
  [29] = 21,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 20,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
};

static const TSCharacterRange sym_sql_token_character_set_1[] = {
  {0, 0x08}, {0x0b, '\f'}, {0x0e, 0x1f}, {'!', '!'}, {'#', '&'}, {'(', ','}, {'.', '.'}, {'0', '9'},
  {';', '?'}, {'A', 'Z'}, {'\\', '_'}, {'a', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(90);
      ADVANCE_MAP(
        '!', 14,
        '"', 4,
        '\'', 6,
        '(', 107,
        ')', 108,
        ',', 121,
        '-', 10,
        '/', 7,
        ':', 102,
        '<', 15,
        '=', 122,
        '@', 24,
        '[', 16,
        '`', 17,
        'f', 92,
        't', 96,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 4,
        '\'', 6,
        '-', 154,
        '/', 152,
        ':', 156,
        '@', 27,
        '[', 155,
        '`', 17,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0) ADVANCE(157);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 4,
        '\'', 6,
        '-', 154,
        '/', 152,
        ':', 156,
        '@', 46,
        '[', 155,
        '`', 17,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0) ADVANCE(157);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(149);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(6);
      if (lookahead == '-') ADVANCE(87);
      if (lookahead == ':') ADVANCE(88);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 't') ADVANCE(68);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(125);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(147);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 11:
      if (lookahead == '-') ADVANCE(65);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(81);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(123);
      END_STATE();
    case 15:
      if (lookahead == '>') ADVANCE(124);
      END_STATE();
    case 16:
      if (lookahead == ']') ADVANCE(148);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '`') ADVANCE(150);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(73);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(73);
      if (lookahead == 'h') ADVANCE(63);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(83);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(80);
      END_STATE();
    case 23:
      if (lookahead == 'b') ADVANCE(85);
      END_STATE();
    case 24:
      ADVANCE_MAP(
        'c', 19,
        'd', 32,
        'e', 59,
        'f', 53,
        'i', 48,
        'k', 33,
        'o', 66,
        'p', 69,
        'w', 52,
      );
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(53);
      if (lookahead == 'i') ADVANCE(48);
      if (lookahead == 'o') ADVANCE(66);
      if (lookahead == 'w') ADVANCE(52);
      END_STATE();
    case 26:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'c') ADVANCE(18);
      if (lookahead == 'd') ADVANCE(32);
      if (lookahead == 'e') ADVANCE(59);
      if (lookahead == 'k') ADVANCE(33);
      if (lookahead == 'p') ADVANCE(69);
      END_STATE();
    case 28:
      if (lookahead == 'd') ADVANCE(111);
      END_STATE();
    case 29:
      if (lookahead == 'd') ADVANCE(54);
      END_STATE();
    case 30:
      if (lookahead == 'd') ADVANCE(55);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(113);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(112);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(119);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(118);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(129);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 48:
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(120);
      END_STATE();
    case 49:
      if (lookahead == 'f') ADVANCE(20);
      END_STATE();
    case 50:
      if (lookahead == 'f') ADVANCE(109);
      END_STATE();
    case 51:
      if (lookahead == 'h') ADVANCE(63);
      END_STATE();
    case 52:
      if (lookahead == 'h') ADVANCE(40);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(56);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 58:
      if (lookahead == 'l') ADVANCE(76);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(110);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(64);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(74);
      END_STATE();
    case 65:
      if (lookahead == 'p') ADVANCE(71);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(47);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(34);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 75:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 76:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 77:
      if (lookahead == 't') ADVANCE(114);
      END_STATE();
    case 78:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 82:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 83:
      if (lookahead == 'u') ADVANCE(57);
      END_STATE();
    case 84:
      if (lookahead == 'y') ADVANCE(116);
      END_STATE();
    case 85:
      if (lookahead == 'y') ADVANCE(115);
      END_STATE();
    case 86:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(86);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 87:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 88:
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 89:
      if (eof) ADVANCE(90);
      ADVANCE_MAP(
        '"', 4,
        '\'', 6,
        '-', 153,
        '/', 152,
        ':', 156,
        '@', 25,
        '[', 155,
        '`', 17,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(89);
      if (lookahead != 0) ADVANCE(157);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_header_token1);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'a') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'e') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'e') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'l') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'r') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 's') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (lookahead == 'u') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_header_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_header_token3);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_param_directive_token1);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_param_directive_token2);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_param_directive_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_column_directive_token1);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_ATif_DASHpresent);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_ATendif);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_ATwhen);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_ATend);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_ATchoose);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_ATcase);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_ATdefault);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_ATorder_DASHby);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_ATkey);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_ATfilter_DASHtree_BANG);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(anon_sym_ATfilter_DASHtree);
      if (lookahead == '!') ADVANCE(117);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(anon_sym_ATpredicate);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_ATin);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_literal_token1);
      if (lookahead == '\'') ADVANCE(6);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_literal_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == ':') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '@') ADVANCE(136);
      if (lookahead == 'n') ADVANCE(133);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'a') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'a') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'a') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'c') ADVANCE(143);
      if (lookahead == 'p') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'e') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'l') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'm') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'm') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'm') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'n') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'o') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'r') ADVANCE(135);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'u') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(146);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_quoted_ident);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_quoted_ident);
      if (lookahead == '"') ADVANCE(4);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_quoted_ident);
      if (lookahead == '`') ADVANCE(17);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_param_ref);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_sql_token);
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_sql_token);
      if (lookahead == '-') ADVANCE(132);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_sql_token);
      if (lookahead == '-') ADVANCE(146);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_sql_token);
      if (lookahead == ']') ADVANCE(148);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_sql_token);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(151);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_sql_token);
      if ((!eof && set_contains(sym_sql_token_character_set_1, 12, lookahead))) ADVANCE(157);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 89},
  [2] = {.lex_state = 89},
  [3] = {.lex_state = 89},
  [4] = {.lex_state = 89},
  [5] = {.lex_state = 89},
  [6] = {.lex_state = 89},
  [7] = {.lex_state = 89},
  [8] = {.lex_state = 89},
  [9] = {.lex_state = 89},
  [10] = {.lex_state = 89},
  [11] = {.lex_state = 89},
  [12] = {.lex_state = 89},
  [13] = {.lex_state = 89},
  [14] = {.lex_state = 89},
  [15] = {.lex_state = 89},
  [16] = {.lex_state = 89},
  [17] = {.lex_state = 89},
  [18] = {.lex_state = 89},
  [19] = {.lex_state = 89},
  [20] = {.lex_state = 89},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 86},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 86},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 86},
  [59] = {.lex_state = 86},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 86},
  [62] = {.lex_state = 86},
  [63] = {.lex_state = 89},
  [64] = {.lex_state = 86},
  [65] = {.lex_state = 86},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 86},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 86},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 86},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 86},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_header_token1] = ACTIONS(1),
    [aux_sym_header_token2] = ACTIONS(1),
    [aux_sym_param_directive_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_column_directive_token1] = ACTIONS(1),
    [anon_sym_ATif_DASHpresent] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_ATwhen] = ACTIONS(1),
    [anon_sym_ATend] = ACTIONS(1),
    [anon_sym_ATchoose] = ACTIONS(1),
    [anon_sym_ATcase] = ACTIONS(1),
    [anon_sym_ATdefault] = ACTIONS(1),
    [anon_sym_ATorder_DASHby] = ACTIONS(1),
    [anon_sym_ATkey] = ACTIONS(1),
    [anon_sym_ATfilter_DASHtree_BANG] = ACTIONS(1),
    [anon_sym_ATfilter_DASHtree] = ACTIONS(1),
    [anon_sym_ATpredicate] = ACTIONS(1),
    [anon_sym_ATin] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [aux_sym_literal_token1] = ACTIONS(1),
    [aux_sym_literal_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
    [sym_quoted_ident] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(93),
    [sym__item] = STATE(2),
    [sym__construct] = STATE(2),
    [sym_header] = STATE(2),
    [sym_param_directive] = STATE(2),
    [sym_column_directive] = STATE(2),
    [sym_if_present_block] = STATE(2),
    [sym_when_block] = STATE(2),
    [sym_choose_block] = STATE(2),
    [sym_order_by_block] = STATE(2),
    [sym_filter_tree_block] = STATE(2),
    [sym_in_expr] = STATE(2),
    [sym__sql_content] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_header_token1] = ACTIONS(5),
    [aux_sym_param_directive_token1] = ACTIONS(7),
    [aux_sym_column_directive_token1] = ACTIONS(9),
    [anon_sym_ATif_DASHpresent] = ACTIONS(11),
    [anon_sym_ATwhen] = ACTIONS(13),
    [anon_sym_ATchoose] = ACTIONS(15),
    [anon_sym_ATorder_DASHby] = ACTIONS(17),
    [anon_sym_ATfilter_DASHtree_BANG] = ACTIONS(19),
    [anon_sym_ATfilter_DASHtree] = ACTIONS(21),
    [anon_sym_ATin] = ACTIONS(23),
    [aux_sym_literal_token1] = ACTIONS(25),
    [sym_comment] = ACTIONS(27),
    [sym_block_comment] = ACTIONS(29),
    [sym_quoted_ident] = ACTIONS(29),
    [sym_param_ref] = ACTIONS(29),
    [sym_sql_token] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(5), 1,
      aux_sym_header_token1,
    ACTIONS(7), 1,
      aux_sym_param_directive_token1,
    ACTIONS(9), 1,
      aux_sym_column_directive_token1,
    ACTIONS(11), 1,
      anon_sym_ATif_DASHpresent,
    ACTIONS(13), 1,
      anon_sym_ATwhen,
    ACTIONS(15), 1,
      anon_sym_ATchoose,
    ACTIONS(17), 1,
      anon_sym_ATorder_DASHby,
    ACTIONS(19), 1,
      anon_sym_ATfilter_DASHtree_BANG,
    ACTIONS(21), 1,
      anon_sym_ATfilter_DASHtree,
    ACTIONS(23), 1,
      anon_sym_ATin,
    ACTIONS(25), 1,
      aux_sym_literal_token1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 2,
      sym_comment,
      sym_sql_token,
    ACTIONS(35), 3,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
    STATE(3), 14,
      sym__item,
      sym__construct,
      sym_header,
      sym_param_directive,
      sym_column_directive,
      sym_if_present_block,
      sym_when_block,
      sym_choose_block,
      sym_order_by_block,
      sym_filter_tree_block,
      sym_in_expr,
      sym__sql_content,
      sym_string,
      aux_sym_document_repeat1,
  [62] = 15,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      aux_sym_header_token1,
    ACTIONS(42), 1,
      aux_sym_param_directive_token1,
    ACTIONS(45), 1,
      aux_sym_column_directive_token1,
    ACTIONS(48), 1,
      anon_sym_ATif_DASHpresent,
    ACTIONS(51), 1,
      anon_sym_ATwhen,
    ACTIONS(54), 1,
      anon_sym_ATchoose,
    ACTIONS(57), 1,
      anon_sym_ATorder_DASHby,
    ACTIONS(60), 1,
      anon_sym_ATfilter_DASHtree_BANG,
    ACTIONS(63), 1,
      anon_sym_ATfilter_DASHtree,
    ACTIONS(66), 1,
      anon_sym_ATin,
    ACTIONS(69), 1,
      aux_sym_literal_token1,
    ACTIONS(72), 2,
      sym_comment,
      sym_sql_token,
    ACTIONS(75), 3,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
    STATE(3), 14,
      sym__item,
      sym__construct,
      sym_header,
      sym_param_directive,
      sym_column_directive,
      sym_if_present_block,
      sym_when_block,
      sym_choose_block,
      sym_order_by_block,
      sym_filter_tree_block,
      sym_in_expr,
      sym__sql_content,
      sym_string,
      aux_sym_document_repeat1,
  [124] = 2,
    ACTIONS(80), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(78), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [146] = 2,
    ACTIONS(84), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(82), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [168] = 2,
    ACTIONS(88), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(86), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [190] = 2,
    ACTIONS(92), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(90), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [212] = 2,
    ACTIONS(96), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(94), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [234] = 2,
    ACTIONS(100), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(98), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [256] = 2,
    ACTIONS(104), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(102), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [278] = 2,
    ACTIONS(108), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(106), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [300] = 2,
    ACTIONS(112), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(110), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [322] = 2,
    ACTIONS(116), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(114), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [344] = 2,
    ACTIONS(120), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(118), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [366] = 2,
    ACTIONS(124), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(122), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [388] = 2,
    ACTIONS(128), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(126), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [410] = 2,
    ACTIONS(132), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(130), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [432] = 2,
    ACTIONS(136), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(134), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [454] = 2,
    ACTIONS(140), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(138), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [476] = 2,
    ACTIONS(144), 3,
      anon_sym_ATfilter_DASHtree,
      sym_comment,
      sym_sql_token,
    ACTIONS(142), 14,
      ts_builtin_sym_end,
      aux_sym_header_token1,
      aux_sym_param_directive_token1,
      aux_sym_column_directive_token1,
      anon_sym_ATif_DASHpresent,
      anon_sym_ATwhen,
      anon_sym_ATchoose,
      anon_sym_ATorder_DASHby,
      anon_sym_ATfilter_DASHtree_BANG,
      anon_sym_ATin,
      aux_sym_literal_token1,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [498] = 5,
    ACTIONS(148), 1,
      aux_sym_literal_token1,
    ACTIONS(154), 1,
      sym_sql_token,
    STATE(21), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(151), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
    ACTIONS(146), 5,
      anon_sym_ATend,
      anon_sym_ATcase,
      anon_sym_ATdefault,
      anon_sym_ATkey,
      anon_sym_ATpredicate,
  [523] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(163), 1,
      sym_sql_token,
    ACTIONS(157), 3,
      anon_sym_ATend,
      anon_sym_ATcase,
      anon_sym_ATdefault,
    STATE(25), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(161), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [546] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(169), 1,
      sym_sql_token,
    ACTIONS(165), 3,
      anon_sym_ATend,
      anon_sym_ATdefault,
      anon_sym_ATkey,
    STATE(21), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(167), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [569] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(175), 1,
      sym_sql_token,
    ACTIONS(171), 3,
      anon_sym_ATend,
      anon_sym_ATdefault,
      anon_sym_ATkey,
    STATE(23), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(173), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [592] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(169), 1,
      sym_sql_token,
    ACTIONS(177), 3,
      anon_sym_ATend,
      anon_sym_ATcase,
      anon_sym_ATdefault,
    STATE(21), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(167), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [615] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(169), 1,
      sym_sql_token,
    ACTIONS(179), 2,
      anon_sym_ATend,
      anon_sym_ATpredicate,
    STATE(21), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(167), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [637] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(185), 1,
      sym_sql_token,
    ACTIONS(181), 2,
      anon_sym_ATend,
      anon_sym_ATpredicate,
    STATE(26), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(183), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [659] = 2,
    ACTIONS(144), 1,
      sym_sql_token,
    ACTIONS(142), 10,
      anon_sym_ATend,
      anon_sym_ATcase,
      anon_sym_ATdefault,
      anon_sym_ATkey,
      anon_sym_ATpredicate,
      aux_sym_literal_token1,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [675] = 5,
    ACTIONS(146), 1,
      anon_sym_ATendif,
    ACTIONS(187), 1,
      aux_sym_literal_token1,
    ACTIONS(193), 1,
      sym_sql_token,
    STATE(29), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(190), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [696] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(196), 1,
      anon_sym_ATend,
    ACTIONS(200), 1,
      sym_sql_token,
    STATE(34), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(198), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [717] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(169), 1,
      sym_sql_token,
    ACTIONS(202), 1,
      anon_sym_ATend,
    STATE(21), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(167), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [738] = 5,
    ACTIONS(204), 1,
      anon_sym_ATendif,
    ACTIONS(206), 1,
      aux_sym_literal_token1,
    ACTIONS(210), 1,
      sym_sql_token,
    STATE(29), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(208), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [759] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(212), 1,
      anon_sym_ATend,
    ACTIONS(216), 1,
      sym_sql_token,
    STATE(31), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(214), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [780] = 5,
    ACTIONS(159), 1,
      aux_sym_literal_token1,
    ACTIONS(169), 1,
      sym_sql_token,
    ACTIONS(218), 1,
      anon_sym_ATend,
    STATE(21), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(167), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [801] = 5,
    ACTIONS(206), 1,
      aux_sym_literal_token1,
    ACTIONS(220), 1,
      anon_sym_ATendif,
    ACTIONS(224), 1,
      sym_sql_token,
    STATE(32), 3,
      sym__sql_content,
      sym_string,
      aux_sym_if_present_block_repeat1,
    ACTIONS(222), 4,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [822] = 2,
    ACTIONS(144), 1,
      sym_sql_token,
    ACTIONS(142), 6,
      anon_sym_ATendif,
      aux_sym_literal_token1,
      sym_comment,
      sym_block_comment,
      sym_quoted_ident,
      sym_param_ref,
  [834] = 5,
    ACTIONS(226), 1,
      anon_sym_ATend,
    ACTIONS(228), 1,
      anon_sym_ATcase,
    ACTIONS(230), 1,
      anon_sym_ATdefault,
    STATE(68), 1,
      sym_default_clause,
    STATE(42), 2,
      sym_case_clause,
      aux_sym_choose_block_repeat1,
  [851] = 5,
    ACTIONS(228), 1,
      anon_sym_ATcase,
    ACTIONS(230), 1,
      anon_sym_ATdefault,
    ACTIONS(232), 1,
      anon_sym_ATend,
    STATE(74), 1,
      sym_default_clause,
    STATE(37), 2,
      sym_case_clause,
      aux_sym_choose_block_repeat1,
  [868] = 5,
    ACTIONS(230), 1,
      anon_sym_ATdefault,
    ACTIONS(234), 1,
      anon_sym_ATend,
    ACTIONS(236), 1,
      anon_sym_ATkey,
    STATE(57), 1,
      sym_default_clause,
    STATE(40), 2,
      sym_key_clause,
      aux_sym_order_by_block_repeat1,
  [885] = 5,
    ACTIONS(230), 1,
      anon_sym_ATdefault,
    ACTIONS(236), 1,
      anon_sym_ATkey,
    ACTIONS(238), 1,
      anon_sym_ATend,
    STATE(54), 1,
      sym_default_clause,
    STATE(41), 2,
      sym_key_clause,
      aux_sym_order_by_block_repeat1,
  [902] = 3,
    ACTIONS(242), 1,
      anon_sym_ATkey,
    ACTIONS(240), 2,
      anon_sym_ATend,
      anon_sym_ATdefault,
    STATE(41), 2,
      sym_key_clause,
      aux_sym_order_by_block_repeat1,
  [914] = 3,
    ACTIONS(247), 1,
      anon_sym_ATcase,
    ACTIONS(245), 2,
      anon_sym_ATend,
      anon_sym_ATdefault,
    STATE(42), 2,
      sym_case_clause,
      aux_sym_choose_block_repeat1,
  [926] = 2,
    STATE(86), 1,
      sym_literal,
    ACTIONS(250), 4,
      aux_sym_literal_token1,
      aux_sym_literal_token2,
      anon_sym_true,
      anon_sym_false,
  [936] = 3,
    ACTIONS(252), 1,
      anon_sym_ATend,
    ACTIONS(254), 1,
      anon_sym_ATpredicate,
    STATE(44), 2,
      sym_predicate_clause,
      aux_sym_filter_tree_block_repeat1,
  [947] = 3,
    ACTIONS(257), 1,
      anon_sym_ATend,
    ACTIONS(259), 1,
      anon_sym_ATpredicate,
    STATE(44), 2,
      sym_predicate_clause,
      aux_sym_filter_tree_block_repeat1,
  [958] = 2,
    STATE(43), 1,
      sym_comparison,
    ACTIONS(261), 3,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_GT,
  [967] = 1,
    ACTIONS(263), 4,
      aux_sym_literal_token1,
      aux_sym_literal_token2,
      anon_sym_true,
      anon_sym_false,
  [974] = 3,
    ACTIONS(259), 1,
      anon_sym_ATpredicate,
    ACTIONS(265), 1,
      anon_sym_ATend,
    STATE(45), 2,
      sym_predicate_clause,
      aux_sym_filter_tree_block_repeat1,
  [985] = 3,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    ACTIONS(269), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_parameter_list_repeat1,
  [995] = 3,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    STATE(51), 1,
      aux_sym_parameter_list_repeat1,
  [1005] = 3,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_parameter_list_repeat1,
  [1015] = 1,
    ACTIONS(267), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1020] = 2,
    ACTIONS(278), 1,
      aux_sym_header_token2,
    STATE(73), 1,
      sym_parameter_list,
  [1027] = 1,
    ACTIONS(280), 1,
      anon_sym_ATend,
  [1031] = 1,
    ACTIONS(282), 1,
      aux_sym_header_token2,
  [1035] = 1,
    ACTIONS(284), 1,
      anon_sym_LPAREN,
  [1039] = 1,
    ACTIONS(238), 1,
      anon_sym_ATend,
  [1043] = 1,
    ACTIONS(286), 1,
      aux_sym_header_token2,
  [1047] = 1,
    ACTIONS(288), 1,
      aux_sym_header_token2,
  [1051] = 1,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
  [1055] = 1,
    ACTIONS(292), 1,
      aux_sym_header_token2,
  [1059] = 1,
    ACTIONS(294), 1,
      aux_sym_header_token2,
  [1063] = 1,
    ACTIONS(296), 1,
      sym_param_ref,
  [1067] = 1,
    ACTIONS(298), 1,
      aux_sym_header_token2,
  [1071] = 1,
    ACTIONS(300), 1,
      aux_sym_header_token2,
  [1075] = 1,
    ACTIONS(302), 1,
      anon_sym_LPAREN,
  [1079] = 1,
    ACTIONS(304), 1,
      aux_sym_param_directive_token2,
  [1083] = 1,
    ACTIONS(306), 1,
      anon_sym_ATend,
  [1087] = 1,
    ACTIONS(308), 1,
      aux_sym_param_directive_token2,
  [1091] = 1,
    ACTIONS(310), 1,
      aux_sym_header_token2,
  [1095] = 1,
    ACTIONS(312), 1,
      aux_sym_header_token3,
  [1099] = 1,
    ACTIONS(314), 1,
      anon_sym_COLON,
  [1103] = 1,
    ACTIONS(316), 1,
      anon_sym_RPAREN,
  [1107] = 1,
    ACTIONS(226), 1,
      anon_sym_ATend,
  [1111] = 1,
    ACTIONS(318), 1,
      anon_sym_RPAREN,
  [1115] = 1,
    ACTIONS(320), 1,
      anon_sym_RPAREN,
  [1119] = 1,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
  [1123] = 1,
    ACTIONS(324), 1,
      anon_sym_RPAREN,
  [1127] = 1,
    ACTIONS(326), 1,
      anon_sym_RPAREN,
  [1131] = 1,
    ACTIONS(328), 1,
      anon_sym_RPAREN,
  [1135] = 1,
    ACTIONS(330), 1,
      anon_sym_RPAREN,
  [1139] = 1,
    ACTIONS(332), 1,
      anon_sym_LPAREN,
  [1143] = 1,
    ACTIONS(334), 1,
      anon_sym_RPAREN,
  [1147] = 1,
    ACTIONS(336), 1,
      anon_sym_LPAREN,
  [1151] = 1,
    ACTIONS(338), 1,
      aux_sym_header_token2,
  [1155] = 1,
    ACTIONS(340), 1,
      anon_sym_RPAREN,
  [1159] = 1,
    ACTIONS(342), 1,
      anon_sym_LPAREN,
  [1163] = 1,
    ACTIONS(344), 1,
      anon_sym_COLON,
  [1167] = 1,
    ACTIONS(346), 1,
      anon_sym_LPAREN,
  [1171] = 1,
    ACTIONS(348), 1,
      anon_sym_LPAREN,
  [1175] = 1,
    ACTIONS(350), 1,
      aux_sym_header_token2,
  [1179] = 1,
    ACTIONS(352), 1,
      anon_sym_LPAREN,
  [1183] = 1,
    ACTIONS(354), 1,
      ts_builtin_sym_end,
  [1187] = 1,
    ACTIONS(356), 1,
      aux_sym_header_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 62,
  [SMALL_STATE(4)] = 124,
  [SMALL_STATE(5)] = 146,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 190,
  [SMALL_STATE(8)] = 212,
  [SMALL_STATE(9)] = 234,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 278,
  [SMALL_STATE(12)] = 300,
  [SMALL_STATE(13)] = 322,
  [SMALL_STATE(14)] = 344,
  [SMALL_STATE(15)] = 366,
  [SMALL_STATE(16)] = 388,
  [SMALL_STATE(17)] = 410,
  [SMALL_STATE(18)] = 432,
  [SMALL_STATE(19)] = 454,
  [SMALL_STATE(20)] = 476,
  [SMALL_STATE(21)] = 498,
  [SMALL_STATE(22)] = 523,
  [SMALL_STATE(23)] = 546,
  [SMALL_STATE(24)] = 569,
  [SMALL_STATE(25)] = 592,
  [SMALL_STATE(26)] = 615,
  [SMALL_STATE(27)] = 637,
  [SMALL_STATE(28)] = 659,
  [SMALL_STATE(29)] = 675,
  [SMALL_STATE(30)] = 696,
  [SMALL_STATE(31)] = 717,
  [SMALL_STATE(32)] = 738,
  [SMALL_STATE(33)] = 759,
  [SMALL_STATE(34)] = 780,
  [SMALL_STATE(35)] = 801,
  [SMALL_STATE(36)] = 822,
  [SMALL_STATE(37)] = 834,
  [SMALL_STATE(38)] = 851,
  [SMALL_STATE(39)] = 868,
  [SMALL_STATE(40)] = 885,
  [SMALL_STATE(41)] = 902,
  [SMALL_STATE(42)] = 914,
  [SMALL_STATE(43)] = 926,
  [SMALL_STATE(44)] = 936,
  [SMALL_STATE(45)] = 947,
  [SMALL_STATE(46)] = 958,
  [SMALL_STATE(47)] = 967,
  [SMALL_STATE(48)] = 974,
  [SMALL_STATE(49)] = 985,
  [SMALL_STATE(50)] = 995,
  [SMALL_STATE(51)] = 1005,
  [SMALL_STATE(52)] = 1015,
  [SMALL_STATE(53)] = 1020,
  [SMALL_STATE(54)] = 1027,
  [SMALL_STATE(55)] = 1031,
  [SMALL_STATE(56)] = 1035,
  [SMALL_STATE(57)] = 1039,
  [SMALL_STATE(58)] = 1043,
  [SMALL_STATE(59)] = 1047,
  [SMALL_STATE(60)] = 1051,
  [SMALL_STATE(61)] = 1055,
  [SMALL_STATE(62)] = 1059,
  [SMALL_STATE(63)] = 1063,
  [SMALL_STATE(64)] = 1067,
  [SMALL_STATE(65)] = 1071,
  [SMALL_STATE(66)] = 1075,
  [SMALL_STATE(67)] = 1079,
  [SMALL_STATE(68)] = 1083,
  [SMALL_STATE(69)] = 1087,
  [SMALL_STATE(70)] = 1091,
  [SMALL_STATE(71)] = 1095,
  [SMALL_STATE(72)] = 1099,
  [SMALL_STATE(73)] = 1103,
  [SMALL_STATE(74)] = 1107,
  [SMALL_STATE(75)] = 1111,
  [SMALL_STATE(76)] = 1115,
  [SMALL_STATE(77)] = 1119,
  [SMALL_STATE(78)] = 1123,
  [SMALL_STATE(79)] = 1127,
  [SMALL_STATE(80)] = 1131,
  [SMALL_STATE(81)] = 1135,
  [SMALL_STATE(82)] = 1139,
  [SMALL_STATE(83)] = 1143,
  [SMALL_STATE(84)] = 1147,
  [SMALL_STATE(85)] = 1151,
  [SMALL_STATE(86)] = 1155,
  [SMALL_STATE(87)] = 1159,
  [SMALL_STATE(88)] = 1163,
  [SMALL_STATE(89)] = 1167,
  [SMALL_STATE(90)] = 1171,
  [SMALL_STATE(91)] = 1175,
  [SMALL_STATE(92)] = 1179,
  [SMALL_STATE(93)] = 1183,
  [SMALL_STATE(94)] = 1187,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_present_block, 6, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_present_block, 6, 0, 4),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column_directive, 4, 0, 3),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column_directive, 4, 0, 3),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_expr, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_in_expr, 4, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_present_block, 5, 0, 4),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_present_block, 5, 0, 4),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choose_block, 5, 0, 5),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choose_block, 5, 0, 5),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order_by_block, 5, 0, 5),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_order_by_block, 5, 0, 5),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_tree_block, 5, 0, 5),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_tree_block, 5, 0, 5),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 3, 0, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 3, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choose_block, 6, 0, 5),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choose_block, 6, 0, 5),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order_by_block, 6, 0, 5),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_order_by_block, 6, 0, 5),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_tree_block, 6, 0, 5),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_tree_block, 6, 0, 5),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_directive, 4, 0, 2),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_param_directive, 4, 0, 2),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_block, 7, 0, 6),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_when_block, 7, 0, 6),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choose_block, 7, 0, 5),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choose_block, 7, 0, 5),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_order_by_block, 7, 0, 5),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_order_by_block, 7, 0, 5),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_block, 8, 0, 6),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_when_block, 8, 0, 6),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [154] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_clause, 4, 0, 7),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_clause, 5, 0, 8),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_clause, 4, 0, 8),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_case_clause, 5, 0, 7),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_clause, 5, 0, 9),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_clause, 4, 0, 9),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [190] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [193] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_if_present_block_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_clause, 2, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_clause, 1, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_order_by_block_repeat1, 2, 0, 0),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_order_by_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_choose_block_repeat1, 2, 0, 0),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_choose_block_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filter_tree_block_repeat1, 2, 0, 0),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_filter_tree_block_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [269] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [354] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sqletch(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "sqletch",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
